### ISSUE TITLE
compilemessages not working

### ISSUE THREAD

**Issue by kjde** [mathiasertl/django-xmpp-account#14]
I can't use the command compilemessages. 

```
$ virtualenv .
$ source bin/activate
$ git fetch
$ git pull origin master
From https://github.com/mathiasertl/django-xmpp-account
 * branch            master     -> FETCH_HEAD
Already up-to-date.

$ python manage.py compilemessages
CommandError: This script should be run from the Django Git checkout or your project or app tree, or with the settings module specified.
```

But as you can see I am in the git/project directory. I don't get it.

**Comment by mathiasertl** [comment]
like the docs now say, please execute `compilemessages` inside the app directories. Alternatively, run `manage.py update`, which executes `collectstatic`, `migrate` and the respective `compilemessages` - it's a one-stop-shop to have everything up-to-date ;-).
