### ISSUE TITLE
can't upgrade anymore

### ISSUE THREAD

**Issue by kjde** [mathiasertl/django-xmpp-account#15]
Yesterday I tried to update my installation but I am stopped by celery.

It is a Debian 7 with python 2.7.

Here ist what I get in the shell: https://gist.github.com/kjde/aca109704708668a0a37

**Comment by mathiasertl** [comment]
Unfortunately I cannot reproduce this:

```
(django-xmpp-account)mati@dt:~/git/mati/django-xmpp-account$ python manage.py update
/usr/bin/gpg --status-fd 2 --no-tty --homedir /home/mati/git/mati/django-xmpp-account/.gpg --lock-multiple --version
Operations to perform:
  Synchronize unmigrated apps: staticfiles, reset, register, messages, delete
  Apply all migrations: core, sessions, admin, auth, captcha, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
processing file django.po in /home/mati/git/mati/django-xmpp-account/core/locale/de/LC_MESSAGES
processing file django.po in /home/mati/git/mati/django-xmpp-account/register/locale/de/LC_MESSAGES
processing file django.po in /home/mati/git/mati/django-xmpp-account/reset/locale/de/LC_MESSAGES
processing file django.po in /home/mati/git/mati/django-xmpp-account/delete/locale/de/LC_MESSAGES
```

Can you try manually starting a python shell and do `from celery import Celery`? This could be (just a guess, of course) caused if importing celery itself works (which is clearly in the requirements) but some dependency caused by your configuration is not installed, causing the line in question to throw an ImportError.

**Comment by kjde** [comment]
I had to change the requirements.txt to django-simple-captcha==0.4.5 and it seems that django is working again.

The bad part is, that it can't communicate with ejabberd. Every call gets an Error -118 "{error,account_unprivileged}". 

I just tried your ejabberd config from jabber.at but it doesn't even start: https://gist.github.com/kjde/eb20278475f9ba53a4c0

Everything is so damn frustrating if you just want an private xmpp server for a small bunch of people. I'm thinking of stopping my work. Also because of such great error messages like "{undefined_macro,''}", but it's not your part.

**Comment by mathiasertl** [comment]
I"m sorry you have such a hard time setting this up. Reading your log closer, there is an error message by pip:

```
Downloading/unpacking django-simple-captcha==0.4.6 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement django-simple-captcha==0.4.6 (from -r requirements.txt (line 6)) (from versions: )
No distributions matching the version for django-simple-captcha==0.4.6 (from -r requirements.txt (line 6))
```

... which means that it couldn't install django-simple-captcha. You could try reproducing the problem with `pip install --no-cache-dir django-simple-captcha==0.4.6` and inspect the log files. It might also help (just a guess, and please tell me if it does, so I can update the docs) to do a `pip install -U pip setuptools`.

**Comment by mathiasertl** [comment]
As for your ejabberd problems, `{error,account_unprivileged}` means (I think) that you have configured wrong configuration credentials. Here is what we currently use (passwords and account names are changed, of course):

normal ejabberd config:

```
acl:
  xmlrpc:
    user:
      - "username": "jabber.at"

access:
  xmlrpc:
    xmlrpc: allow
```

then the xmlrpc.cfg:
```
{listen, [
  {{4560, "::"}, ejabberd_xmlrpc, [{maxsessions, 10}, {timeout, 5000},
    {access_commands, [
      {xmlrpc, [register, set_last, check_account, check_password, change_password, send_message, registered_users, unregister], []}
    ]}
  ]}
]}.
```

And in xmpp-accounts `localsettings.py`:

```
XMPP_BACKENDS = {
    'default': {
        'BACKEND': 'xmpp_backends.ejabberd_xmlrpc.EjabberdXMLRPCBackend',
        'uri': 'http://jabber.at:4560',
        'user': 'username',
        'server': 'jabber.at',
        'password': 'password',
   },
}
```

**Comment by mathiasertl** [comment]
Two more things to note:

* I recently moved the backends to [xmpp-backends](https://github.com/mathiasertl/xmpp-backends) so it can be reused by other projects. This brings the change in option names (`HOST` -> `uri` and so on). The old backends should continue to work with the same options for the time being, though.
* ejabberds `mod_xmlrpc` is super-picky about credentials. If you have not defined `access_commands` (this means that no authentication is required to access xmlrpc) you actually *must not* define `user`, `server` and `password`.

**Comment by kjde** [comment]
It's so embrassing but I found an error in my ejabberd config. yay
It seems, that the conversion from oldstyle to yml with ejabberdctl didn't work flawless.

**Comment by mathiasertl** [comment]
I vaguely remember there were some problems with it somehow with the last ejabberd version. Not sure what exactly the state is. But good the problem is solved for you.
