### ISSUE TITLE
cannot disable GNUPG

### ISSUE THREAD

**Issue by kjde** [mathiasertl/django-xmpp-account#16]
It seems like there is an error when GNUPG is disabled via "GNUPG = None"

https://gist.github.com/kjde/33ad55228e52bdf9f745

**Comment by mathiasertl** [comment]
Acknowledged, fill fix this in the evening...

**Comment by mathiasertl** [comment]
I hope this fixes everything. If there are still places were this doesn't work, please don't hesitate to reopen the issue.
