### ISSUE TITLE
Offer XMPP URI after registration (link / QR Code)

### ISSUE THREAD

**Issue by iNPUTmice** [mathiasertl/django-xmpp-account#17]
Hi,

what about offering a XMPP URI in the style of ````xmpp://username:password@server.tld```` in form of both a clickable link and a QR code.
That would make the registration process a lot more stream lined as I could drop users into the registration page and would have a way to get them back into my client without having them reenter the username and password they just chose.

**Comment by mathiasertl** [comment]
hmm, I'm not sure. Definitely an improvement for some, but at least my browser (or the majority?!) the link displays a "address not understood" type-of message. [XEP-0147](http://xmpp.org/extensions/xep-0147.html) further defines `xmpp:username@domain` (note the missing slashes).

**Comment by mathiasertl** [comment]
I'm not at all happy with out-of-band registration in XMPP. AFAIK you (as a client developer) can't even tell a registration URL for a particular server (you might hardcode some?), right?

Maybe we should write an XEP that defines a registration URL stream feature (so your client can open that URL), and then a way for the XMPP server to call back the client with the registration data.

**Comment by iNPUTmice** [comment]
````xmpp:alice@domain.tld```` is used to open a conversation with Alice. ````xmpp://username:password@server.tld```` could be used to open a connection to the server.tld with username and password. At least if we follow general URI schemas. (In an extreme case they could be combined like ```xmpp:alice@domain.tld://username:password@server.tld```)

> hmm, I'm not sure. Definitely an improvement for some, but at least my browser (or the majority?!) the link displays a "address not understood" type-of message.

I think on most operating systems now days programs can register to listen to these URI schemas. Meaning your chat client can make your browser understand this link. If that's not the case now that's at least something client developers could do. And it's not violating any rules or standards. And users don't *have to* client the link.

> AFAIK you (as a client developer) can't even tell a registration URL for a particular server (you might hardcode some?), right?

Well to allow for easier onboarding / registration I - at some point - have to hard code a list of servers ie make some recommendations. And at this point it doesn't matter whether I hard code the registration website or the servers domain (and have the client discover the registration website on it's own.) 
Granted a auto discovery for a web url would be nicer but I wouldn't regard it as a blocker for having the xmpp-uri at the end of the registration process.

(Plus I think inband registration can communicate an URL)

**Comment by mathiasertl** [comment]
I'm closing this, it makes the situation worse for most users.

**Comment by ralphm** [comment]
Even if this is closed, for future onlookers like me, I want to point out that the example with authority component above should look like this: `xmpp://username:password@server.tld/alice@domain.tld`.
